# coding: utf-8

"""
    Snowplow Signals API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.feature_output import FeatureOutput


class TestFeatureOutput(unittest.TestCase):
    """FeatureOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeatureOutput:
        """Test FeatureOutput
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FeatureOutput`
        """
        model = FeatureOutput()
        if include_optional:
            return FeatureOutput(
                name = '',
                description = '',
                dtype = 'UNKNOWN',
                tags = {
                    'key' : ''
                    },
                vector_index = True,
                vector_search_metric = '',
                scope = 'session',
                events = [
                    ''
                    ],
                type = 'counter',
                var_property = '',
                filter = openapi_client.models.filter_combinator.FilterCombinator(
                    combinator = 'and', 
                    condition = [
                        openapi_client.models.filter_condition.FilterCondition(
                            property = '', 
                            operator = 'equals', 
                            value = null, )
                        ], ),
                signals_derived = True
            )
        else:
            return FeatureOutput(
                name = '',
                scope = 'session',
                events = [
                    ''
                    ],
                type = 'counter',
        )
        """

    def testFeatureOutput(self):
        """Test FeatureOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
