# coding: utf-8

"""
    Snowplow Signals API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.prompt_base import PromptBase


class TestPromptBase(unittest.TestCase):
    """PromptBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptBase:
        """Test PromptBase
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PromptBase`
        """
        model = PromptBase()
        if include_optional:
            return PromptBase(
                name = 'H0',
                version = 1.0,
                prompt = '0',
                features = [
                    openapi_client.models.feature_ref.FeatureRef(
                        name = '0', 
                        reference = '', )
                    ],
                labels = [
                    'production'
                    ],
                tags = [
                    ''
                    ],
                author = '',
                commit_msg = ''
            )
        else:
            return PromptBase(
                name = 'H0',
                version = 1.0,
                prompt = '0',
                features = [
                    openapi_client.models.feature_ref.FeatureRef(
                        name = '0', 
                        reference = '', )
                    ],
                labels = [
                    'production'
                    ],
                tags = [
                    ''
                    ],
                author = '',
                commit_msg = '',
        )
        """

    def testPromptBase(self):
        """Test PromptBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
