# coding: utf-8

"""
    Snowplow Signals API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.feature_view_input import FeatureViewInput


class TestFeatureViewInput(unittest.TestCase):
    """FeatureViewInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeatureViewInput:
        """Test FeatureViewInput
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `FeatureViewInput`
        """
        model = FeatureViewInput()
        if include_optional:
            return FeatureViewInput(
                name = '',
                version = 56,
                entities = [
                    openapi_client.models.entity_link.EntityLink(
                        name = '', )
                    ],
                ttl = '',
                source = openapi_client.models.data_source_link.DataSourceLink(
                    name = '', ),
                online = True,
                description = '',
                tags = {
                    'key' : ''
                    },
                owner = '',
                fields = [
                    openapi_client.models.field.Field(
                        name = '', 
                        description = '', 
                        dtype = 'UNKNOWN', 
                        tags = {
                            'key' : ''
                            }, 
                        vector_index = True, 
                        vector_search_metric = '', )
                    ],
                features = [
                    openapi_client.models.feature.Feature(
                        name = '', 
                        description = '', 
                        dtype = 'UNKNOWN', 
                        tags = {
                            'key' : ''
                            }, 
                        vector_index = True, 
                        vector_search_metric = '', 
                        scope = 'session', 
                        events = [
                            ''
                            ], 
                        type = 'counter', 
                        property = '', 
                        filter = openapi_client.models.filter_combinator.FilterCombinator(
                            combinator = 'and', 
                            condition = [
                                openapi_client.models.filter_condition.FilterCondition(
                                    property = '', 
                                    operator = 'equals', 
                                    value = null, )
                                ], ), 
                        signals_derived = True, )
                    ],
                status = 'Draft'
            )
        else:
            return FeatureViewInput(
                name = '',
        )
        """

    def testFeatureViewInput(self):
        """Test FeatureViewInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
