# coding: utf-8

"""
    Snowplow Signals API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.feature_store_api import FeatureStoreApi


class TestFeatureStoreApi(unittest.TestCase):
    """FeatureStoreApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FeatureStoreApi()

    def tearDown(self) -> None:
        pass

    def test_apply_to_feast_api_v1_feature_store_apply_post(self) -> None:
        """Test case for apply_to_feast_api_v1_feature_store_apply_post

        Apply To Feast
        """
        pass

    def test_get_feast_data_sources_api_v1_feature_store_data_sources_get(self) -> None:
        """Test case for get_feast_data_sources_api_v1_feature_store_data_sources_get

        Get Feast Data Sources
        """
        pass

    def test_get_feast_feature_services_api_v1_feature_store_feature_services_get(
        self,
    ) -> None:
        """Test case for get_feast_feature_services_api_v1_feature_store_feature_services_get

        Get Feast Feature Services
        """
        pass

    def test_get_feast_feature_views_api_v1_feature_store_feature_views_get(
        self,
    ) -> None:
        """Test case for get_feast_feature_views_api_v1_feature_store_feature_views_get

        Get Feast Feature Views
        """
        pass


if __name__ == "__main__":
    unittest.main()
