# coding: utf-8

"""
    Snowplow Signals API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.registry_api import RegistryApi


class TestRegistryApi(unittest.TestCase):
    """RegistryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RegistryApi()

    def tearDown(self) -> None:
        pass

    def test_create_data_source_api_v1_registry_data_sources_post(self) -> None:
        """Test case for create_data_source_api_v1_registry_data_sources_post

        Create Data Source
        """
        pass

    def test_create_entity_api_v1_registry_entities_post(self) -> None:
        """Test case for create_entity_api_v1_registry_entities_post

        Create Entity
        """
        pass

    def test_create_feature_service_api_v1_registry_feature_services_post(self) -> None:
        """Test case for create_feature_service_api_v1_registry_feature_services_post

        Create Feature Service
        """
        pass

    def test_create_feature_view_api_v1_registry_feature_views_post(self) -> None:
        """Test case for create_feature_view_api_v1_registry_feature_views_post

        Create Feature View
        """
        pass

    def test_delete_data_source_api_v1_registry_data_sources_data_source_name_delete(
        self,
    ) -> None:
        """Test case for delete_data_source_api_v1_registry_data_sources_data_source_name_delete

        Delete Data Source
        """
        pass

    def test_delete_entity_api_v1_registry_entities_entity_name_delete(self) -> None:
        """Test case for delete_entity_api_v1_registry_entities_entity_name_delete

        Delete Entity
        """
        pass

    def test_delete_feature_service_api_v1_registry_feature_services_feature_service_name_delete(
        self,
    ) -> None:
        """Test case for delete_feature_service_api_v1_registry_feature_services_feature_service_name_delete

        Delete Feature Service
        """
        pass

    def test_delete_feature_view_api_v1_registry_feature_views_feature_view_name_versions_version_delete(
        self,
    ) -> None:
        """Test case for delete_feature_view_api_v1_registry_feature_views_feature_view_name_versions_version_delete

        Delete Feature View
        """
        pass

    def test_get_all_data_sources_api_v1_registry_data_sources_get(self) -> None:
        """Test case for get_all_data_sources_api_v1_registry_data_sources_get

        Get All Data Sources
        """
        pass

    def test_get_all_entities_api_v1_registry_entities_get(self) -> None:
        """Test case for get_all_entities_api_v1_registry_entities_get

        Get All Entities
        """
        pass

    def test_get_all_feature_services_api_v1_registry_feature_services_get(
        self,
    ) -> None:
        """Test case for get_all_feature_services_api_v1_registry_feature_services_get

        Get All Feature Services
        """
        pass

    def test_get_all_feature_views_api_v1_registry_feature_views_get(self) -> None:
        """Test case for get_all_feature_views_api_v1_registry_feature_views_get

        Get All Feature Views
        """
        pass

    def test_get_data_source_api_v1_registry_data_sources_data_source_name_get(
        self,
    ) -> None:
        """Test case for get_data_source_api_v1_registry_data_sources_data_source_name_get

        Get Data Source
        """
        pass

    def test_get_entity_api_v1_registry_entities_entity_name_get(self) -> None:
        """Test case for get_entity_api_v1_registry_entities_entity_name_get

        Get Entity
        """
        pass

    def test_get_feature_service_api_v1_registry_feature_services_feature_service_name_get(
        self,
    ) -> None:
        """Test case for get_feature_service_api_v1_registry_feature_services_feature_service_name_get

        Get Feature Service
        """
        pass

    def test_get_feature_view_with_version_api_v1_registry_feature_views_feature_view_name_versions_version_get(
        self,
    ) -> None:
        """Test case for get_feature_view_with_version_api_v1_registry_feature_views_feature_view_name_versions_version_get

        Get Feature View With Version
        """
        pass

    def test_get_latest_feature_view_api_v1_registry_feature_views_feature_view_name_get(
        self,
    ) -> None:
        """Test case for get_latest_feature_view_api_v1_registry_feature_views_feature_view_name_get

        Get Latest Feature View
        """
        pass


if __name__ == "__main__":
    unittest.main()
