# coding: utf-8

"""
    Snowplow Signals API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.data_source import DataSource


class TestDataSource(unittest.TestCase):
    """DataSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataSource:
        """Test DataSource
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DataSource`
        """
        model = DataSource()
        if include_optional:
            return DataSource(
                name = '',
                type = 'push',
                timestamp_field = '',
                created_timestamp_column = '',
                field_mapping = {
                    'key' : ''
                    },
                description = '',
                tags = {
                    'key' : ''
                    },
                owner = '',
                date_partition_column = '',
                database = '',
                var_schema = '',
                table = '',
                query = '',
                path = '',
                batch_source = openapi_client.models.data_source_link.DataSourceLink(
                    name = '', )
            )
        else:
            return DataSource(
                name = '',
        )
        """

    def testDataSource(self):
        """Test DataSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
