# coding: utf-8

"""
    Snowplow Signals API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.prompt_deleted_response import PromptDeletedResponse


class TestPromptDeletedResponse(unittest.TestCase):
    """PromptDeletedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptDeletedResponse:
        """Test PromptDeletedResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PromptDeletedResponse`
        """
        model = PromptDeletedResponse()
        if include_optional:
            return PromptDeletedResponse(
                ok = True
            )
        else:
            return PromptDeletedResponse(
                ok = True,
        )
        """

    def testPromptDeletedResponse(self):
        """Test PromptDeletedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
