# coding: utf-8

"""
    Snowplow Signals API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.features_api import FeaturesApi


class TestFeaturesApi(unittest.TestCase):
    """FeaturesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FeaturesApi()

    def tearDown(self) -> None:
        pass

    def test_get_online_features_api_v1_get_online_features_post(self) -> None:
        """Test case for get_online_features_api_v1_get_online_features_post

        Get Online Features
        """
        pass

    def test_push_api_v1_push_post(self) -> None:
        """Test case for push_api_v1_push_post

        Push
        """
        pass


if __name__ == "__main__":
    unittest.main()
