# coding: utf-8

"""
    Snowplow Signals API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.prompts_api import PromptsApi


class TestPromptsApi(unittest.TestCase):
    """PromptsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PromptsApi()

    def tearDown(self) -> None:
        pass

    def test_create_prompt_api_v1_prompts_post(self) -> None:
        """Test case for create_prompt_api_v1_prompts_post

        Create Prompt
        """
        pass

    def test_delete_prompt_api_v1_prompts_prompt_name_version_version_delete(
        self,
    ) -> None:
        """Test case for delete_prompt_api_v1_prompts_prompt_name_version_version_delete

        Delete Prompt
        """
        pass

    def test_get_latest_prompt_api_v1_prompts_prompt_name_get(self) -> None:
        """Test case for get_latest_prompt_api_v1_prompts_prompt_name_get

        Get Latest Prompt
        """
        pass

    def test_get_prompt_api_v1_prompts_prompt_name_version_version_get(self) -> None:
        """Test case for get_prompt_api_v1_prompts_prompt_name_version_version_get

        Get Prompt
        """
        pass

    def test_get_prompts_api_v1_prompts_get(self) -> None:
        """Test case for get_prompts_api_v1_prompts_get

        Get Prompts
        """
        pass

    def test_hydrate_prompt_api_v1_prompts_prompt_name_version_version_hydrate_post(
        self,
    ) -> None:
        """Test case for hydrate_prompt_api_v1_prompts_prompt_name_version_version_hydrate_post

        Hydrate Prompt
        """
        pass


if __name__ == "__main__":
    unittest.main()
