# coding: utf-8

"""
    Snowplow Signals API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.prompt_response import PromptResponse


class TestPromptResponse(unittest.TestCase):
    """PromptResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptResponse:
        """Test PromptResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PromptResponse`
        """
        model = PromptResponse()
        if include_optional:
            return PromptResponse(
                name = 'H0',
                version = 1.0,
                prompt = '0',
                features = [
                    openapi_client.models.feature_ref.FeatureRef(
                        name = '0', 
                        reference = '', )
                    ],
                labels = [
                    'production'
                    ],
                tags = [
                    ''
                    ],
                author = '',
                commit_msg = '',
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return PromptResponse(
                name = 'H0',
                version = 1.0,
                prompt = '0',
                features = [
                    openapi_client.models.feature_ref.FeatureRef(
                        name = '0', 
                        reference = '', )
                    ],
                labels = [
                    'production'
                    ],
                tags = [
                    ''
                    ],
                author = '',
                commit_msg = '',
                id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testPromptResponse(self):
        """Test PromptResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
