# coding: utf-8

"""
    Snowplow Signals API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from openapi_client.models.data_source_link import DataSourceLink
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self


class DataSource(BaseModel):
    """
    DataSource that can be used to source features.
    """  # noqa: E501

    name: StrictStr = Field(description="The unique name of the object.")
    type: Optional[StrictStr] = Field(
        default="push", description="The type of data source."
    )
    timestamp_field: Optional[StrictStr] = None
    created_timestamp_column: Optional[StrictStr] = None
    field_mapping: Optional[Dict[str, StrictStr]] = None
    description: Optional[StrictStr] = None
    tags: Optional[Dict[str, StrictStr]] = None
    owner: Optional[StrictStr] = None
    date_partition_column: Optional[StrictStr] = None
    database: Optional[StrictStr] = None
    var_schema: Optional[StrictStr] = Field(default=None, alias="schema")
    table: Optional[StrictStr] = None
    query: Optional[StrictStr] = None
    path: Optional[StrictStr] = None
    batch_source: Optional[DataSourceLink] = None
    __properties: ClassVar[List[str]] = [
        "name",
        "type",
        "timestamp_field",
        "created_timestamp_column",
        "field_mapping",
        "description",
        "tags",
        "owner",
        "date_partition_column",
        "database",
        "schema",
        "table",
        "query",
        "path",
        "batch_source",
    ]

    @field_validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["push", "snowflake", "file"]):
            raise ValueError("must be one of enum values ('push', 'snowflake', 'file')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataSource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of batch_source
        if self.batch_source:
            _dict["batch_source"] = self.batch_source.to_dict()
        # set to None if timestamp_field (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp_field is None and "timestamp_field" in self.model_fields_set:
            _dict["timestamp_field"] = None

        # set to None if created_timestamp_column (nullable) is None
        # and model_fields_set contains the field
        if (
            self.created_timestamp_column is None
            and "created_timestamp_column" in self.model_fields_set
        ):
            _dict["created_timestamp_column"] = None

        # set to None if field_mapping (nullable) is None
        # and model_fields_set contains the field
        if self.field_mapping is None and "field_mapping" in self.model_fields_set:
            _dict["field_mapping"] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict["description"] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict["tags"] = None

        # set to None if owner (nullable) is None
        # and model_fields_set contains the field
        if self.owner is None and "owner" in self.model_fields_set:
            _dict["owner"] = None

        # set to None if date_partition_column (nullable) is None
        # and model_fields_set contains the field
        if (
            self.date_partition_column is None
            and "date_partition_column" in self.model_fields_set
        ):
            _dict["date_partition_column"] = None

        # set to None if database (nullable) is None
        # and model_fields_set contains the field
        if self.database is None and "database" in self.model_fields_set:
            _dict["database"] = None

        # set to None if var_schema (nullable) is None
        # and model_fields_set contains the field
        if self.var_schema is None and "var_schema" in self.model_fields_set:
            _dict["schema"] = None

        # set to None if table (nullable) is None
        # and model_fields_set contains the field
        if self.table is None and "table" in self.model_fields_set:
            _dict["table"] = None

        # set to None if query (nullable) is None
        # and model_fields_set contains the field
        if self.query is None and "query" in self.model_fields_set:
            _dict["query"] = None

        # set to None if path (nullable) is None
        # and model_fields_set contains the field
        if self.path is None and "path" in self.model_fields_set:
            _dict["path"] = None

        # set to None if batch_source (nullable) is None
        # and model_fields_set contains the field
        if self.batch_source is None and "batch_source" in self.model_fields_set:
            _dict["batch_source"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataSource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "type": obj.get("type") if obj.get("type") is not None else "push",
                "timestamp_field": obj.get("timestamp_field"),
                "created_timestamp_column": obj.get("created_timestamp_column"),
                "field_mapping": obj.get("field_mapping"),
                "description": obj.get("description"),
                "tags": obj.get("tags"),
                "owner": obj.get("owner"),
                "date_partition_column": obj.get("date_partition_column"),
                "database": obj.get("database"),
                "schema": obj.get("schema"),
                "table": obj.get("table"),
                "query": obj.get("query"),
                "path": obj.get("path"),
                "batch_source": (
                    DataSourceLink.from_dict(obj["batch_source"])
                    if obj.get("batch_source") is not None
                    else None
                ),
            }
        )
        return _obj
