# coding: utf-8

"""
    Snowplow Signals API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from openapi_client.models.feature_view_link import FeatureViewLink
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self


class FeatureService(BaseModel):
    """
    A feature service defines a logical group of features from one or more feature views. This group of features can be retrieved together during training or serving.
    """  # noqa: E501

    name: StrictStr = Field(description="The unique name of the object.")
    description: Optional[StrictStr] = None
    feature_views: Optional[List[FeatureViewLink]] = Field(
        default=None,
        description="A list containing feature views and feature view projections, representing the features in the feature service.",
    )
    tags: Optional[Dict[str, StrictStr]] = None
    owner: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "name",
        "description",
        "feature_views",
        "tags",
        "owner",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeatureService from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in feature_views (list)
        _items = []
        if self.feature_views:
            for _item_feature_views in self.feature_views:
                if _item_feature_views:
                    _items.append(_item_feature_views.to_dict())
            _dict["feature_views"] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict["description"] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict["tags"] = None

        # set to None if owner (nullable) is None
        # and model_fields_set contains the field
        if self.owner is None and "owner" in self.model_fields_set:
            _dict["owner"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeatureService from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "description": obj.get("description"),
                "feature_views": (
                    [FeatureViewLink.from_dict(_item) for _item in obj["feature_views"]]
                    if obj.get("feature_views") is not None
                    else None
                ),
                "tags": obj.get("tags"),
                "owner": obj.get("owner"),
            }
        )
        return _obj
