# coding: utf-8

"""
    Snowplow Signals API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from openapi_client.models.data_source_link import DataSourceLink
from openapi_client.models.entity_link import EntityLink
from openapi_client.models.feature_output import FeatureOutput
from openapi_client.models.model_field import ModelField
from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictInt,
    StrictStr,
    field_validator,
)
from typing_extensions import Self


class FeatureViewOutput(BaseModel):
    """
    A FeatureView defines a logical group of features.
    """  # noqa: E501

    name: StrictStr = Field(description="The unique name of the feature view.")
    version: Optional[StrictInt] = Field(
        default=1, description="The version of the feature view."
    )
    entities: Optional[List[EntityLink]] = Field(
        default=None,
        description="The list of names of entities that this feature view is associated with.",
    )
    ttl: Optional[StrictStr] = None
    source: Optional[DataSourceLink] = None
    online: Optional[StrictBool] = Field(
        default=True,
        description="A boolean indicating whether online retrieval is enabled for this feature view.",
    )
    description: Optional[StrictStr] = None
    tags: Optional[Dict[str, StrictStr]] = None
    owner: Optional[StrictStr] = None
    fields: Optional[List[ModelField]] = Field(
        default=None,
        description="The schema of the feature view, including timestamp, and entity columns. If not specified, can be inferred from the underlying data source.",
    )
    features: Optional[List[FeatureOutput]] = Field(
        default=None,
        description="The list of features that are part of this feature view.",
    )
    status: Optional[StrictStr] = Field(
        default="Draft", description="The status of the feature view."
    )
    feast_name: StrictStr
    __properties: ClassVar[List[str]] = [
        "name",
        "version",
        "entities",
        "ttl",
        "source",
        "online",
        "description",
        "tags",
        "owner",
        "fields",
        "features",
        "status",
        "feast_name",
    ]

    @field_validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["Draft", "QA", "Live"]):
            raise ValueError("must be one of enum values ('Draft', 'QA', 'Live')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeatureViewOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "feast_name",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in entities (list)
        _items = []
        if self.entities:
            for _item_entities in self.entities:
                if _item_entities:
                    _items.append(_item_entities.to_dict())
            _dict["entities"] = _items
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict["source"] = self.source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in fields (list)
        _items = []
        if self.fields:
            for _item_fields in self.fields:
                if _item_fields:
                    _items.append(_item_fields.to_dict())
            _dict["fields"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in features (list)
        _items = []
        if self.features:
            for _item_features in self.features:
                if _item_features:
                    _items.append(_item_features.to_dict())
            _dict["features"] = _items
        # set to None if ttl (nullable) is None
        # and model_fields_set contains the field
        if self.ttl is None and "ttl" in self.model_fields_set:
            _dict["ttl"] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict["source"] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict["description"] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict["tags"] = None

        # set to None if owner (nullable) is None
        # and model_fields_set contains the field
        if self.owner is None and "owner" in self.model_fields_set:
            _dict["owner"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeatureViewOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "version": obj.get("version") if obj.get("version") is not None else 1,
                "entities": (
                    [EntityLink.from_dict(_item) for _item in obj["entities"]]
                    if obj.get("entities") is not None
                    else None
                ),
                "ttl": obj.get("ttl"),
                "source": (
                    DataSourceLink.from_dict(obj["source"])
                    if obj.get("source") is not None
                    else None
                ),
                "online": obj.get("online") if obj.get("online") is not None else True,
                "description": obj.get("description"),
                "tags": obj.get("tags"),
                "owner": obj.get("owner"),
                "fields": (
                    [ModelField.from_dict(_item) for _item in obj["fields"]]
                    if obj.get("fields") is not None
                    else None
                ),
                "features": (
                    [FeatureOutput.from_dict(_item) for _item in obj["features"]]
                    if obj.get("features") is not None
                    else None
                ),
                "status": (
                    obj.get("status") if obj.get("status") is not None else "Draft"
                ),
                "feast_name": obj.get("feast_name"),
            }
        )
        return _obj
