# coding: utf-8

"""
    Snowplow Signals API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictStr,
    field_validator,
)
from typing_extensions import Self


class ModelField(BaseModel):
    """
    A Field represents a set of values with the same structure.
    """  # noqa: E501

    name: StrictStr = Field(description="The name of the field.")
    description: Optional[StrictStr] = None
    dtype: Optional[StrictStr] = Field(
        default="UNKNOWN", description="The type of the field, such as string or float."
    )
    tags: Optional[Dict[str, StrictStr]] = None
    vector_index: Optional[StrictBool] = Field(
        default=False,
        description="If set to True the field will be indexed for vector similarity search.",
    )
    vector_search_metric: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = [
        "name",
        "description",
        "dtype",
        "tags",
        "vector_index",
        "vector_search_metric",
    ]

    @field_validator("dtype")
    def dtype_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(
            [
                "UNKNOWN",
                "BYTES",
                "STRING",
                "INT32",
                "INT64",
                "DOUBLE",
                "FLOAT",
                "BOOL",
                "UNIX_TIMESTAMP",
                "BYTES_LIST",
                "STRING_LIST",
                "INT32_LIST",
                "INT64_LIST",
                "DOUBLE_LIST",
                "FLOAT_LIST",
                "BOOL_LIST",
                "UNIX_TIMESTAMP_LIST",
                "NULL",
            ]
        ):
            raise ValueError(
                "must be one of enum values ('UNKNOWN', 'BYTES', 'STRING', 'INT32', 'INT64', 'DOUBLE', 'FLOAT', 'BOOL', 'UNIX_TIMESTAMP', 'BYTES_LIST', 'STRING_LIST', 'INT32_LIST', 'INT64_LIST', 'DOUBLE_LIST', 'FLOAT_LIST', 'BOOL_LIST', 'UNIX_TIMESTAMP_LIST', 'NULL')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ModelField from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict["description"] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict["tags"] = None

        # set to None if vector_search_metric (nullable) is None
        # and model_fields_set contains the field
        if (
            self.vector_search_metric is None
            and "vector_search_metric" in self.model_fields_set
        ):
            _dict["vector_search_metric"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ModelField from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "description": obj.get("description"),
                "dtype": (
                    obj.get("dtype") if obj.get("dtype") is not None else "UNKNOWN"
                ),
                "tags": obj.get("tags"),
                "vector_index": (
                    obj.get("vector_index")
                    if obj.get("vector_index") is not None
                    else False
                ),
                "vector_search_metric": obj.get("vector_search_metric"),
            }
        )
        return _obj
