# coding: utf-8

"""
    Snowplow Signals API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing_extensions import Self


class PushFeaturesRequest(BaseModel):
    """
    PushFeaturesRequest
    """  # noqa: E501

    push_source_name: StrictStr
    df: Dict[str, List[Any]]
    allow_registry_cache: Optional[StrictBool] = True
    to: Optional[StrictStr] = "online"
    __properties: ClassVar[List[str]] = [
        "push_source_name",
        "df",
        "allow_registry_cache",
        "to",
    ]

    @field_validator("to")
    def to_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["online", "online_and_offline"]):
            raise ValueError(
                "must be one of enum values ('online', 'online_and_offline')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PushFeaturesRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PushFeaturesRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "push_source_name": obj.get("push_source_name"),
                "df": obj.get("df"),
                "allow_registry_cache": (
                    obj.get("allow_registry_cache")
                    if obj.get("allow_registry_cache") is not None
                    else True
                ),
                "to": obj.get("to") if obj.get("to") is not None else "online",
            }
        )
        return _obj
