mock_attribute_views = [
    {
        "name": "ecommerce_transaction_interactions_features",
        "version": 1,
        "entity": {"name": "user"},
        "ttl": None,
        "batch_source": {
            "name": "ecommerce_transaction_interactions_source",
            "timestamp_field": "UPDATED_AT",
            "created_timestamp_column": None,
            "description": None,
            "tags": None,
            "owner": None,
            "date_partition_column": None,
            "database": "SNOWPLOW_DEV1",
            "schema": None,
            "table": "SNOWPLOW_ECOMMERCE_TRANSACTION_INTERACTIONS_FEATURES",
        },
        "online": True,
        "description": None,
        "tags": None,
        "owner": None,
        "fields": [
            {
                "name": "TOTAL_TRANSACTIONS",
                "description": None,
                "type": "int32",
                "tags": None,
            },
            {
                "name": "TOTAL_REVENUE",
                "description": None,
                "type": "int32",
                "tags": None,
            },
            {
                "name": "AVG_TRANSACTION_REVENUE",
                "description": None,
                "type": "int32",
                "tags": None,
            },
        ],
        "attributes": [],
        "feast_name": "ecommerce_transaction_interactions_features_v1",
        "offline": True,
        "stream_source_name": "ecommerce_transaction_interactions_features_stream",
        "entity_key": "user",
        "view_or_entity_ttl": None,
    },
    {
        "name": "unified_users_features",
        "version": 1,
        "entity": {"name": "user"},
        "ttl": None,
        "batch_source": {
            "name": "snowplow_unified_users_source",
            "timestamp_field": "UPDATED_AT",
            "created_timestamp_column": None,
            "description": None,
            "tags": None,
            "owner": None,
            "date_partition_column": None,
            "database": "SNOWPLOW_DEV1",
            "schema": None,
            "table": "SNOWPLOW_UNIFIED_USERS_FEATURES",
        },
        "online": True,
        "description": None,
        "tags": None,
        "owner": None,
        "fields": [
            {"name": "DAYS_ACTIVE", "description": None, "type": "int32", "tags": None},
            {
                "name": "ACTIVE_TIME_IN_SECONDS",
                "description": None,
                "type": "int32",
                "tags": None,
            },
            {
                "name": "AVG_SESSION_DURATION",
                "description": None,
                "type": "int32",
                "tags": None,
            },
        ],
        "attributes": [],
        "feast_name": "unified_users_features_v1",
        "offline": True,
        "stream_source_name": "unified_users_features_stream",
        "entity_key": "user",
        "view_or_entity_ttl": None,
    },
]


def get_attribute_view_response():
    return mock_attribute_views
